### ISSUE TITLE
20240122 회의 (상태관리 이슈)

### ISSUE THREAD

**Issue by yunsunglee2** [whtjdrud/team4_openmind#14]
**직면한 문제** 
질문작성, 답변하기 페이지 컴포넌트를 재활용이 가능하게 id값을 활용해 api에서 데이터들을 받아오게 만들고 싶다. -> 
누구에게 질문할까요? 질문작성, 답변하기 페이지들은 부모관계가 아니다 -> 질문할 사람 카드 클릭시 받아온 id를 공유할수 없다 ->
페이지를 이동하는 클릭 이벤트가 발생한다면 클릭당한 유저의 id 상태관리가 필요하다. 

**해결책** 
useRecoil 라이브러리를 사용하자

1. '로그인' 페이지에서 이름 작성 후 질문받기 클릭 시, post 해주고 생성한 id 값은 localStorage에서 관리 

2. '누구에게 질문할까요?' 페이지에서 질문 카드를 클릭 시, 클릭한 카드 user의 id값을 api에서 get해서 atom 객체에 set해주기 
2-1. 클릭 이벤트가 발생하면 페이지 이동, 이동경로는 atom객체에 set해준 값을 받아와 경로 지정 

4.  '질문 작성' 페이지에서는 '누구에게 질문할까요?'페이지에서 set해준 id을 atom객체에서 가져와 경로 등록
4-1. 페이지 안의 데이터들은 가져온 id를 활용해 api에서 id에 맞는 정보들을 불러오기. (질문을 받는 사람의 프로필 사진, 질문을 받는 사람에게 남겨진 질문들과 답변)
4-2. 질문 작성시, 질문을 남기는 사람의 정보는 localStorage에 저장된 id를 활용해서 질문을 남긴 사람의 정보를 post해주기. 

5. '답변 작성' 페이지에서는 로컬 스토리지에 저장된 id를 이용해 페이지 상단의 프로필 이미지와 남겨진 질문들 가져오기
5-1. 남겨진 질문에 대한 답변을 등록할때 localStorage에 담겨진 id로 post해주기.

![스크린샷 2024-01-22 15 30 52](https://github.com/whtjdrud/team4_openmind/assets/135799803/ad435780-17d6-4f03-ace5-a78311768a24)

**요약**
로그인 상태는 localStorage에 id를 생성해서 관리 
페이지 이동 클릭 이벤트 발생시 이동한 페이지에서 필요한 데이터를 useRecoilState를 활용한 atom객체에 id 조회해서 api 데이터 불러오기 

**생각해보아야 할것** (중요)
1. 로그인 상태 관리는 왜 localStorage에서 했고 장점은 무엇인지? 
2. 전역 상태관리 방법은 ContextApi, useRecoil 등 다양한 방법이 있는데 useRecoil을 선택한 이유는 무엇이고 어떤점이 좋았는지?

**Comment by ahrrrl** [comment]
이번에 이야기한 걸 잘 정리하신거 같습니다! 2.에 "클릭한 카드 user의 id값을 api에서 get해서" 이 부분은 제가 이미 각 card 속성 key값에 id를 가져온 상태이기 때문에 그 key값을 사용하면 될 거 같습니다! 아 다시 생각해보니 key값뿐만 아니라 card자체 값을 넘기는게 더 좋겠군요 제가 한번 짜보고 보여드리겠습니다!

**Comment by yunsunglee2** [comment]
> 이번에 이야기한 걸 잘 정리하신거 같습니다! 2.에 "클릭한 카드 user의 id값을 api에서 get해서" 이 부분은 제가 이미 각 card 속성 key값에 id를 가져온 상태이기 때문에 그 key값을 사용하면 될 거 같습니다! 아 다시 생각해보니 key값뿐만 아니라 card자체 값을 넘기는게 더 좋겠군요 제가 한번 짜보고 보여드리겠습니다!

**Comment by yunsunglee2** [comment]
넵 저도 최대한 내일까지 만들어보겠습니다
